#!/bin/bash

cd ${_CONDOR_SCRATCH_DIR}

INPUTPATHSFILES=${1}
DATAPUSOURCEWITHXRDPREFIX=${2}
OUTPUTEOSFOLDERWITHXRDPREFIX=${3}
OUTPUTFILENAME_SUMWGTS=${4}
OUTPUTFILENAME_PUWGTS=${5}

echo "getSumMCWeightsHelper.sh called with INPUTPATHSFILES: ${INPUTPATHSFILES}, DATAPUSOURCEWITHXRDPREFIX: ${DATAPUSOURCEWITHXRDPREFIX}, OUTPUTEOSFOLDERWITHXRDPREFIX: ${OUTPUTEOSFOLDERWITHXRDPREFIX}, OUTPUTFILENAME_SUMWGTS: ${OUTPUTFILENAME_SUMWGTS}, OUTPUTFILENAME_PUWGTS: ${OUTPUTFILENAME_PUWGTS}"

source setup_environment_remote.sh

./extract_miscScriptsTarball.sh
cd ${_CONDOR_SCRATCH_DIR}

./miscScripts/bin/getSumMCWeights inputPathsFiles=${INPUTPATHSFILES} dataPUSourceWithXRDPrefix=${DATAPUSOURCEWITHXRDPREFIX} outputFileNameWeights=${OUTPUTFILENAME_SUMWGTS} outputFileNamePU=${OUTPUTFILENAME_PUWGTS}

xrdmv_with_check ${OUTPUTFILENAME_SUMWGTS} ${OUTPUTEOSFOLDERWITHXRDPREFIX}/${OUTPUTFILENAME_SUMWGTS}
xrdmv_with_check ${OUTPUTFILENAME_PUWGTS} ${OUTPUTEOSFOLDERWITHXRDPREFIX}/${OUTPUTFILENAME_PUWGTS}
